# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: res.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='res.proto',
  package='RES',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\tres.proto\x12\x03RES\"\x9e\x01\n\x07\x41\x62ility\x12$\n\x0c\x61\x62ility_list\x18\x01 \x03(\x0b\x32\x0e.RES.Ability.M\x1am\n\x01M\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tscript_id\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0e\n\x06\x61ttack\x18\x04 \x01(\t\x12\x14\n\x0c\x61\x63tive_skill\x18\x05 \x01(\t\x12\x15\n\rpassive_skill\x18\x06 \x01(\t\"l\n\x0c\x42\x61ttleAction\x12/\n\x12\x62\x61ttle_action_list\x18\x01 \x03(\x0b\x32\x13.RES.BattleAction.M\x1a+\n\x01M\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t\x12\x0c\n\x04para\x18\x03 \x03(\x05\x62\x06proto3'
)




_ABILITY_M = _descriptor.Descriptor(
  name='M',
  full_name='RES.Ability.M',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RES.Ability.M.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='script_id', full_name='RES.Ability.M.script_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='RES.Ability.M.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attack', full_name='RES.Ability.M.attack', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='active_skill', full_name='RES.Ability.M.active_skill', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passive_skill', full_name='RES.Ability.M.passive_skill', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=177,
)

_ABILITY = _descriptor.Descriptor(
  name='Ability',
  full_name='RES.Ability',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ability_list', full_name='RES.Ability.ability_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ABILITY_M, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=177,
)


_BATTLEACTION_M = _descriptor.Descriptor(
  name='M',
  full_name='RES.BattleAction.M',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RES.BattleAction.M.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='RES.BattleAction.M.desc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='para', full_name='RES.BattleAction.M.para', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=287,
)

_BATTLEACTION = _descriptor.Descriptor(
  name='BattleAction',
  full_name='RES.BattleAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='battle_action_list', full_name='RES.BattleAction.battle_action_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BATTLEACTION_M, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=287,
)

_ABILITY_M.containing_type = _ABILITY
_ABILITY.fields_by_name['ability_list'].message_type = _ABILITY_M
_BATTLEACTION_M.containing_type = _BATTLEACTION
_BATTLEACTION.fields_by_name['battle_action_list'].message_type = _BATTLEACTION_M
DESCRIPTOR.message_types_by_name['Ability'] = _ABILITY
DESCRIPTOR.message_types_by_name['BattleAction'] = _BATTLEACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ability = _reflection.GeneratedProtocolMessageType('Ability', (_message.Message,), {

  'M' : _reflection.GeneratedProtocolMessageType('M', (_message.Message,), {
    'DESCRIPTOR' : _ABILITY_M,
    '__module__' : 'res_pb2'
    # @@protoc_insertion_point(class_scope:RES.Ability.M)
    })
  ,
  'DESCRIPTOR' : _ABILITY,
  '__module__' : 'res_pb2'
  # @@protoc_insertion_point(class_scope:RES.Ability)
  })
_sym_db.RegisterMessage(Ability)
_sym_db.RegisterMessage(Ability.M)

BattleAction = _reflection.GeneratedProtocolMessageType('BattleAction', (_message.Message,), {

  'M' : _reflection.GeneratedProtocolMessageType('M', (_message.Message,), {
    'DESCRIPTOR' : _BATTLEACTION_M,
    '__module__' : 'res_pb2'
    # @@protoc_insertion_point(class_scope:RES.BattleAction.M)
    })
  ,
  'DESCRIPTOR' : _BATTLEACTION,
  '__module__' : 'res_pb2'
  # @@protoc_insertion_point(class_scope:RES.BattleAction)
  })
_sym_db.RegisterMessage(BattleAction)
_sym_db.RegisterMessage(BattleAction.M)


# @@protoc_insertion_point(module_scope)
