RES_PROTO_PATH = "..\\res"
GEN_PB_CMD = ".\\make_proto.bat"
DEFAULT_EXCEL_PATH = "..\\table"
CLIENT_DATA_PATH = "..\\data\\client\\"
SERVER_DATA_PATH = "..\\data\\server\\"
PUBLIC_DATA_PATH = "..\\data\\public\\"